[WIP] Prometheus export nodes counter
aws/aws-node-termination-handler pull request #1083
Opened 2024-10-29 14:34 UTC by phuhung273

**Issue #, if available:**
#785 

**Description of changes:**
- Count nodes being tracked

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2024-11-16 09:34 UTC, phuhung273 commented
@stevehipwell can you please give me a help on this. Now i only stuck at writing unit test for `opentelemetry.go` since it doesn
t have any test. 

Do you think i should refactor this file along with this PR or should I open another separate PR (eg: make opentelemetry.go testable)

2024-11-18 17:20 UTC, LikithaVemulapalli commented
Yes I agree with @stevehipwell here, let's separate refactoring PR to have a clear idea on the changes made. @phuhung273 if you want to test your changes for this PR let me know I will approve and run so for the future commits you can verify if the existing tests are working, if there are any conflicts or not, once you change the PR status to ready I will run the workflow, appreciate for your contribution. Thanks!

2024-12-06 01:57 UTC, phuhung273 commented
/remove-lifecycle stale

2024-12-31 23:38 UTC, tiationg-kho commented
Hi @phuhung273, could you resolve the conflicts in `pkg/node/node_test.go`?

2025-01-01 02:35 UTC, phuhung273 commented
Thanks and Happy new year @tiationg-kho. Conflicts resolved

2025-01-06 03:44 UTC, tiationg-kho reviewed
Hi @phuhung273,

Thanks for resolving the conflicts. I have left some comments. 
Also, we can run the e2e test in local (docker desktop) to make sure our modification is valid.
- Run all e2e test cases: `make e2e-test`
- Run certain e2e test case: `./test/k8s-local-cluster-test/run-test -a ./test/e2e/<test-case> -d -b e2e-test`

2025-01-06 03:44 UTC, tiationg-kho commented on pkg/ec2helper/ec2helper.go
> +	nextToken := ""
We could declare token without initialize the empty string as value here.

2025-01-06 03:44 UTC, tiationg-kho commented on pkg/ec2helper/ec2helper.go
> +			Filters: []*ec2.Filter{
Could we add a filter for instance state here?

2025-01-06 03:44 UTC, tiationg-kho commented on pkg/ec2helper/ec2helper.go
> +			len(result.Reservations[0].Instances) == 0 {
We might have nil issue.

Maybe we do not need to treat empty result as error condition?

2025-01-06 03:44 UTC, tiationg-kho commented on pkg/ec2helper/ec2helper.go
> +				if instance.InstanceId == nil {
Might have nil issue here.

2025-01-06 03:44 UTC, tiationg-kho commented on pkg/node/node.go
> +		ids = append(ids, parts[len(parts)-1])
We could add some check here.

2025-01-06 03:44 UTC, tiationg-kho commented on pkg/observability/opentelemetry.go
> +		metrics.initCronMetrics()
We should use a goroutine here.

2025-01-06 03:44 UTC, tiationg-kho commented on pkg/observability/opentelemetry.go
> +func (m Metrics) serveNodeMetrics() {
We could add nil check for both results. (`instanceIdsMap`, `nodeInstanceIds`)

We should not use `instanceIdsMap` in second block if we got error from `GetInstanceIdsMapByTagKey`.

Consider we filter the nodes result based on instances result, we would not have a chance to record any result (nodes > instances). Do you think this is a potential issue?

2025-01-06 03:44 UTC, tiationg-kho commented on cmd/node-termination-handler.go
> +	ec2 := ec2.New(sess)
We should not use `ec2` as var name. This will cause issue in later like init `sqsevent.SQSMonitor`.

2025-01-06 03:44 UTC, tiationg-kho commented on cmd/node-termination-handler.go
> +	cfg := aws.NewConfig().WithRegion(nthConfig.AWSRegion).WithEndpoint(nthConfig.AWSEndpoint).WithSTSRegionalEndpoint(endpoints.RegionalSTSEndpoint)
We have some code to setup aws related config like below. So we should create client after that.
```
if nthConfig.AWSRegion == "" && nodeMetadata.Region != "" {
    nthConfig.AWSRegion = nodeMetadata.Region
} else if nthConfig.AWSRegion == "" && nthConfig.QueueURL != "" {
    nthConfig.AWSRegion = getRegionFromQueueURL(nthConfig.QueueURL)
    log.Debug().Str("Retrieved AWS region from queue-url: \"%s\"", nthConfig.AWSRegion)
}
if nthConfig.AWSRegion == "" && nthConfig.EnableSQSTerminationDraining {
    nthConfig.Print()
    log.Fatal().Msgf("Unable to find the AWS region to process queue events.")
}
```

2025-01-08 13:42 UTC, phuhung273 commented on pkg/ec2helper/ec2helper.go
> +			Filters: []*ec2.Filter{
Of course we can, but I wonder if we should ? I saw cases where instances enter `Stopped` state instead of `Terminated` . Without filterring user can discover such case.

2025-01-08 14:10 UTC, phuhung273 commented on pkg/observability/opentelemetry.go
> +func (m Metrics) serveNodeMetrics() {
Thanks, I have addressed the 2 nil check.

About the edge cases, I did think of if but could not find anyway to do 2 metrics separately:
- For instances we already have a NTH managed tag so we can filter base on it
- For nodes i cannot see any label/annotation that we can filter upon

Therefore, I decided to filter nodes based on instances result. Do you know any info we can use to filter nodes independently

2025-01-08 15:05 UTC, phuhung273 commented on pkg/ec2helper/ec2helper.go
> +	nextToken := ""
Thanks, this is fixed now

2025-01-08 15:06 UTC, phuhung273 commented on pkg/ec2helper/ec2helper.go
> +			len(result.Reservations[0].Instances) == 0 {
Thanks, just added nil check and removed empty array check

2025-01-08 15:07 UTC, phuhung273 commented on pkg/ec2helper/ec2helper.go
> +				if instance.InstanceId == nil {
Thanks, nil check added

2025-01-08 15:08 UTC, phuhung273 commented on pkg/node/node.go
> +		ids = append(ids, parts[len(parts)-1])
Thanks, I have added string split check and 'i-xxxxx' check

2025-01-08 15:08 UTC, phuhung273 commented on pkg/observability/opentelemetry.go
> +		metrics.initCronMetrics()
Yes, modified to use goroutine

2025-01-08 15:09 UTC, phuhung273 commented on cmd/node-termination-handler.go
> +	ec2 := ec2.New(sess)
var name changed to ec2Client

2025-01-08 15:11 UTC, phuhung273 commented on cmd/node-termination-handler.go
> +	cfg := aws.NewConfig().WithRegion(nthConfig.AWSRegion).WithEndpoint(nthConfig.AWSEndpoint).WithSTSRegionalEndpoint(endpoints.RegionalSTSEndpoint)
Thanks, i have moved the metrics initialization after AWS config setup

2025-01-10 23:23 UTC, tiationg-kho commented on pkg/ec2helper/ec2helper.go
> +			Filters: []*ec2.Filter{
Thanks for addressing the comments.

Maybe we could rename `nodesGauge` and `instancesGauge` to let these 2 metrics more self-explain?

Then we could decide we need a filter here or not. And would also know should separate these 2 metrics, or filter one based on another (`opentelemetry.go`).

2025-01-13 15:34 UTC, phuhung273 commented on pkg/ec2helper/ec2helper.go
> +			Filters: []*ec2.Filter{
Thanks, that makes sense. I have renamed to `nthTaggedNodesGauge` and `nthTaggedInstancesGauge`

2025-01-13 15:37 UTC, phuhung273 commented
Thanks @tiationg-kho for your instruction on the e2e test, took a while to realize where does it fail. I will try to include the 2 new metrics in e2e.

2025-01-14 21:55 UTC, tiationg-kho commented on cmd/node-termination-handler.go
> +		go metrics.InitNodeMetrics(node, ec2Client)
We can check `EnablePrometheus` before calling.

2025-01-15 14:22 UTC, phuhung273 commented on cmd/node-termination-handler.go
> +		go metrics.InitNodeMetrics(node, ec2Client)
Thanks, `EnablePrometheus` check added

2025-01-16 14:10 UTC, phuhung273 commented
e2e metrics test in SQS mode added, phew... Please let me know your thought @tiationg-kho, thanks

2025-01-22 22:48 UTC, tiationg-kho reviewed
Thank you for adding a new e2e test case! Just left few comments.

@LikithaVemulapalli could you please take a look too?

2025-01-22 22:48 UTC, tiationg-kho commented on cmd/node-termination-handler.go
> +		if nthConfig.EnablePrometheus {
Could we add nil check for `metrics` here in case we have any error during `observability.InitMetrics`?

2025-01-22 22:48 UTC, tiationg-kho commented on test/e2e/prometheus-metrics-sqs-test
> +        echo "✅ Verified the message was deleted from the queue after processing!"
We could add a `break` here.

2025-01-22 22:48 UTC, tiationg-kho commented on test/e2e/prometheus-metrics-sqs-test
> +for gauge in nth_tagged_instances; do
This cannot pass the shell check (`make shellcheck`).

Could we remove the for-loop and just declare the gauge var like (`gauge="nth_tagged_instances"`)

2025-01-22 23:04 UTC, tiationg-kho commented on test/e2e/prometheus-metrics-sqs-test
> +    echo "❌ regular-pod-test was not evicted"
This check is not quite correct in the context of this test case.

2025-01-23 00:01 UTC, LikithaVemulapalli requested changes
left some inline comments, thanks for your contribution :)

2025-01-26 06:11 UTC, phuhung273 commented on cmd/node-termination-handler.go
> +		if nthConfig.EnablePrometheus {
I tried to, but the compiler doesn't like it

2025-01-26 07:00 UTC, phuhung273 commented on pkg/observability/opentelemetry.go
> +		m.InstancesRecord(int64(len(instanceIdsMap)))
Thank you for spotting this. I should have been more consistent.

2025-01-26 07:04 UTC, phuhung273 commented on test/e2e/prometheus-metrics-sqs-test
> +        echo "✅ Verified the message was deleted from the queue after processing!"
Perfect, appreciate your careful review

2025-01-26 07:11 UTC, phuhung273 commented on test/e2e/prometheus-metrics-sqs-test
> +    echo "❌ regular-pod-test was not evicted"
At first, I just tried to test the 2 new metrics. Later found out that https://github.com/aws/aws-node-termination-handler/blob/main/test/e2e/prometheus-metrics-test only test the metrics in IMDS mode.

So I decided to also include other metrics as well. Thats why the file name is `prometheus-metrics-sqs`: test all metrics in SQS mode. How do you think ?

2025-01-26 08:21 UTC, phuhung273 commented on pkg/ec2helper/ec2helper.go
> +func (h EC2Helper) GetInstanceIdsMapByTagKey(tag string) (map[string]bool, error) {
If I understand correctly, querying DescribeAPI with `tag-key`  only care about the Tag's key, tag's value doesn't matter  https://github.com/aws/aws-node-termination-handler/blob/316906ea1bd59100d1f749cc935253fe65dc1107/pkg/ec2helper/ec2helper.go#L44-L49

2025-01-26 16:30 UTC, phuhung273 commented on pkg/ec2helper/ec2helper.go
> +	if ids == nil {
Thank you, error message modified. Hope it is clear enough.

2025-01-26 16:34 UTC, phuhung273 commented on pkg/ec2helper/ec2helper_test.go
> +package ec2helper_test
My mistake, added 6 more cases here. Please let me know if any more cases should be added.

2025-01-26 16:35 UTC, phuhung273 commented on pkg/node/node.go
> +			ids = append(ids, parts[len(parts)-1])
Thank you, added more info to warning message.

2025-01-26 16:39 UTC, phuhung273 commented on pkg/node/node_test.go
> +func TestFetchKubernetesNodeInstanceIds(t *testing.T) {
Added 2 more test cases, invalid ProviderId case contains 4 invalid samples inside.

2025-01-26 16:52 UTC, phuhung273 commented on test/e2e/prometheus-metrics-sqs-test
> +for gauge in nth_tagged_instances; do
Thank you, will also run shellcheck from now on.

2025-01-26 16:53 UTC, phuhung273 commented on pkg/node/node.go
> +			log.Warn().Msgf("Found invalid providerID: %s", node.Spec.ProviderID)
Yes sir, warning message updated. No more dummy error message from now on.

2025-02-05 19:43 UTC, tiationg-kho commented on test/e2e/prometheus-metrics-sqs-test
> +    echo "❌ regular-pod-test was not evicted"
Maybe we could remove this if-else check, and replace by adding a status variable before `TAINT_CHECK_CYCLES` for-loop, and check it after the for-loop to prevent the misleading scenario here (even we already cordoned and evicted but still get a "not evicted" in our log)?

The metric part is good.

2025-02-05 19:43 UTC, tiationg-kho commented on cmd/node-termination-handler.go
> +		if nthConfig.EnablePrometheus {
Sorry, "nil check" is incorrect. Since we return a zero-value struct when err exists.

Could we rename the error then check that error here?
```
metrics, initMetricsErr := observability.InitMetrics(nthConfig.EnablePrometheus, nthConfig.PrometheusPort)
if initMetricsErr != nil {
    nthConfig.Print()
    log.Fatal().Err(initMetricsErr).Msg("Unable to instantiate observability metrics,")
}
```

2025-02-07 15:22 UTC, phuhung273 commented on cmd/node-termination-handler.go
> +		if nthConfig.EnablePrometheus {
That make sense, understand your idea now. Added `initMetricsErr` nil check. Thank you

2025-02-07 15:31 UTC, phuhung273 commented on test/e2e/prometheus-metrics-sqs-test
> +    echo "❌ regular-pod-test was not evicted"
Oh must be my copy-paste fault :( Removed but I dont understand the status check youre mentioning. Also later part cover the metrics, maybe thats enough ?

2025-02-09 15:32 UTC, phuhung273 commented on test/e2e/prometheus-metrics-sqs-test
> +    echo "❌ regular-pod-test was not evicted"
Thanks for your detailed instruction. Added check for `cordoned`, `evicted`, and `message_deleted`.

2025-02-20 22:18 UTC, tiationg-kho approved these changes
lgtm

2025-02-21 18:19 UTC, LikithaVemulapalli approved these changes
Looks good to me. Appreciate the efforts @phuhung273

2025-02-21 19:44 UTC, LikithaVemulapalli commented
please do not merge change until all the tests are successful. Thanks

2025-02-21 21:33 UTC, merged

2025-02-22 00:29 UTC, phuhung273 commented
Thanks for your kind guidance @tiationg-kho @LikithaVemulapalli