Allow ManagedAsgTag to be configurable
aws/aws-node-termination-handler pull request #287
Opened 2020-11-12 21:58 UTC by blakestoddard

Makes `ManagedAsgTag` a configurable option to allow you to run NTH in queue mode across multiple clusters in an account. EC2 instance events don't have any filtering ability currently, which will cause NTH to drop into a crash loop when it runs into an error while trying to cordon a node that doesn't exist in the cluster. See [here](https://github.com/aws/aws-node-termination-handler/blob/5150b31c819a26c2cc80f812ffb0a0b317290b56/cmd/node-termination-handler.go#L260-L280).

Fixes #272

2020-11-13 16:31 UTC, brycahta requested changes
Looks like build is failing due to unit tests:

* `pkg/monitor/sqsevent/sqs-monitor_internal_test.go:51: undefined: NTHManagedASG`
* `pkg/monitor/sqsevent/sqs-monitor_test.go:542: undefined: NTHManagedASG`

2020-11-16 14:32 UTC, blakestoddard commented
I wasn't sure the best way to really fix that because passing a string to `mockIsManagedTrue` during struct initialization feels just as gross as just updating the constant reference in the function with a new string, so that's what I did.

2020-11-16 18:37 UTC, brycahta requested changes
Looks like **unit tests** are still failing. After some deep dive:

* Looks like you need to initialize [SQSMonitor](https://github.com/aws/aws-node-termination-handler/blob/main/pkg/monitor/sqsevent/sqs-monitor_internal_test.go#L55) with a `ManagedAsgTag` set to the default/tag value; otherwise the `if *tag.Key == m.ManagedAsgTag` fails

2020-11-16 18:41 UTC, brycahta requested changes
Could you also update the **Helm artifacts** in this [folder](https://github.com/aws/aws-node-termination-handler/tree/main/config/helm/aws-node-termination-handler) including ReadMe so that `ManagedAsgTag` can also be configurable as a Helm param? 

the files should be:
* [values.yaml](https://github.com/aws/aws-node-termination-handler/blob/main/config/helm/aws-node-termination-handler/values.yaml)
* [deployment.yaml](https://github.com/aws/aws-node-termination-handler/blob/main/config/helm/aws-node-termination-handler/templates/deployment.yaml)
* [ReadMe](https://github.com/aws/aws-node-termination-handler/tree/main/config/helm/aws-node-termination-handler#aws-node-termination-handler-common-configuration)

edit: removing daemonset configs

2020-11-16 20:16 UTC, blakestoddard commented
I don't see any of the related queue processor variables (`queueURL`, `checkASGTagBeforeDraining`, etc.) defined in the two daemonset configs, so I didn't add those. Should they be?

2020-11-16 20:24 UTC, brycahta commented
> I don't see any of the related queue processor variables (`queueURL`, `checkASGTagBeforeDraining`, etc.) defined in the two daemonset configs, so I didn't add those. Should they be?

Ahh sorry that's my mistake. queue-processor vars shouldn't be in daemonset configs at all; i'll remove from comment

2020-11-17 19:16 UTC, blakestoddard commented
Are those failures in Travis related? Seems like they're from `prometheus-operator`.

2020-11-17 19:31 UTC, brycahta commented
> Are those failures in Travis related? Seems like they're from `prometheus-operator`.

Correct-- these failures aren't related to your changes.

2020-11-17 19:31 UTC, brycahta approved these changes
LGTM 👍🏼

2020-11-17 21:42 UTC, bwagner5 approved these changes
lgtm, thanks!

2020-11-18 14:08 UTC, merged