allow for envFrom on helm chart
aws/aws-node-termination-handler pull request #570
Opened 2022-02-02 19:29 UTC by danquack

Description of changes:
We store a handful of sensitive values in secrets, so this just allows for the envFrom instead of a large array of extraEnv.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2022-02-04 16:20 UTC, snay2 requested changes

2022-02-04 16:20 UTC, snay2 commented on config/helm/aws-node-termination-handler/values.yaml
> +envFrom: []
Can you also add this to the helm chart README? https://github.com/aws/aws-node-termination-handler/blob/main/config/helm/aws-node-termination-handler/README.md?plain=1#L70

2022-02-04 19:10 UTC, snay2 requested changes

2022-02-04 19:10 UTC, snay2 commented on config/helm/aws-node-termination-handler/README.md
> +| `envFrom`                          | Additional environment variables for the _aws-node-termination-handler_ container.
Thanks for adding this. Could you update the description for one or both of the `extraEnv` and `envFrom` parameters to make clear the distinction between them? Some things to consider may be where the parameters are used in the chart and whether their syntax is different.

2022-02-09 12:54 UTC, stevehipwell commented
@danquack do you think it's worth adding `envFrom` instead of using the secret reference directly from `env`? I'm not sure I have a strong opinion but worth considering?

2022-02-10 15:17 UTC, closed without merging