Add option to fetch node name through Kubernetes node .spec.providerID in case custom names are used
aws/aws-node-termination-handler pull request #618
Opened 2022-04-11 10:30 UTC by Ka1wa

**Issue description:**
At our organization we run Kubernetes on EC2 administered with kubeadm. We wanted to add NTH to allow spot instances to be used with proper cordon/draining logic. We use the queue processor mode which means that we receive events through SQS that is then mapped to the `NodeInfo` struct.

```
{
     "InstanceID": "i-1234567890",
     "IsManaged": true,
     "Name": "ip-10.0.0.1.ap-northeast-2.compute.internal",
     "Tags": {
         "Name": "Kubernetes-worker",
         "aws-node-termination-handler/managed": "true",
         "aws:autoscaling:groupName": "Kubernetes-worker",
         "example.com/environment": "testing",
         "example.com/role": "Kubernetes-worker"
     }
 }
```

Now here is the problem: Our nodes have different hostnames from the default `ip-<ip>.<availability-zone>.computer.internal` format. It seems like the Kubernetes node fetching logic only supports the default hostname format which means that node lookup fails and produces the following logs:

```
2022/04/11 02:35:22 INF Error when trying to list Nodes w/ label, falling back to direct Get lookup of node
2022/04/11 02:35:22 ERR Unable to fetch node labels for node 'ip-10.0.0.1.ap-northeast-2.compute.internal'  error="nodes \"ip-10.0.0.1.ap-northeast-2.compute.internal\" not found"
2022/04/11 02:35:22 INF Pods on node node_name=ip-10.0.0.1.ap-northeast-2.compute.internal pod_names=[]
2022/04/11 02:35:22 DBG Not marking for exclusion from load balancers because the configuration flag is not set
2022/04/11 02:35:22 INF Error when trying to list Nodes w/ label, falling back to direct Get lookup of node
2022/04/11 02:35:22 ERR node 'ip-10.0.0.1.ap-northeast-2.compute.internal' not found in the cluster error="nodes \"ip-10.0.0.1.ap-northeast-2.compute.internal\" not found"
```

This PR implements logic that allows the nodes to be selected through the Kubernetes node spec `providerID` field instead. This field is also required for autoscaling (cluster-autoscaler) and has the `aws:///<availabilityzone>/<instanceID>` format. This is also set by EKS clusters.

Because I realize the use of kubelet's `--hostname-override` is probably not a very common concern I implemented the following logic behind a `USE_PROVIDER_ID` environment variable/CLI flag for those running into similar problems as us.

**Description of changes:**
The changes only apply to the Queue mode processor.

* Add `providerID` key/value to `NodeInfo` and `InterruptionEvent`
* Add `GetNodeNameFromProviderID` function to Node struct.
  * This functions loops over all nodes and tries to find a matching ProviderID. (Unfortunately FieldSelector was not supported for this field)
  * When no matching node is found reverts to using node name from the original AWS event.
  * Tries to extract `kubernetes.io/hostname` label first. If unavailable extracts Kubernetes node metadata name instead.
* Add logic into go routine `drainOrCordonIfNecessary` that runs before `GetNodeLabels` that requires the nodeName
* Add `use-provider-id` flag to CLI
* Add `USE_PROVIDER_ID` environment variable (default: false)
* Add configuration tests
* Include option into Helm template and documentation

We currently run this branch in our environment, here are the debug level logs:

```
2022/04/11 07:03:45 DBG Got node info from AWS: {
     "AsgName": "Kubernetes-worker",
     "InstanceID": "i-1234567890",
     "ProviderID": "aws:///ap-northeast-2c/i-1234567890",
     "IsManaged": true,
     "Name": "ip-10-0-0-1.ap-northeast-2.compute.internal",
     "Tags": {
         "Name": "Kubernetes-worker",
         "aws-node-termination-handler/managed": "true",
         "aws:autoscaling:groupName": "Kubernetes-worker",
         "example.com/environment": "testing",
         "example.com/role": "kubernetes-worker"
     }
 }
2022/04/11 07:03:45 DBG Sending SQS_TERMINATE interruption event to the interruption channel
2022/04/11 07:03:45 DBG Checking for queue messages
2022/04/11 07:03:45 INF Adding new event to the event store event={"AutoScalingGroupName":"Kubernetes-worker","Description":"ASG Lifecycle Termination event received. Instance will be interrupted at 2022-04-11 07:03:44 +0000 UTC \n","EndTime":"0001-01-01T00:00:00Z","EventID":"asg-lifecycle-term-9876543210","InProgress":false,"InstanceID":"i-1234567890","IsManaged":true,"Kind":"SQS_TERMINATE","NodeLabels":null,"NodeName":"ip-10-0-0-1.ap-northeast-2.compute.internal","NodeProcessed":false,"Pods":null,"ProviderID":"aws:///ap-northeast-2c/i-1234567890","StartTime":"2022-04-11T07:03:44Z","State":""}
2022/04/11 07:03:45 INF Requesting instance drain event-id=asg-lifecycle-term-9876543210 instance-id=i-1234567890 kind=SQS_TERMINATE node-name=ip-10-0-0-1.ap-northeast-2.compute.internal provider-id=aws:///ap-northeast-2c/i-1234567890
2022/04/11 07:03:45 INF Pods on node node_name=ip-10-0-0-1 pod_names=["calico-node-bzckb","ebs-csi-node-jl4mx","kube-proxy-mktdj","prometheus-node-exporter-fscjc","filebeat-pxwwv"]
2022/04/11 07:03:45 DBG Not marking for exclusion from load balancers because the configuration flag is not set
2022/04/11 07:03:45 INF Draining the node
2022/04/11 07:03:45 ??? WARNING: ignoring DaemonSet-managed Pods: kube-system/calico-node-bzckb, kube-system/ebs-csi-node-jl4mx, kube-system/kube-proxy-mktdj, monitoring/prometheus-node-exporter-fscjc, monitoring/filebeat-pxwwv
2022/04/11 07:03:45 INF Node successfully cordoned and drained node_name=ip-10-0-0-1 reason="ASG Lifecycle Termination event received. Instance will be interrupted at 2022-04-11 07:03:44 +0000 UTC \n"
```

As this is my first pull request on this repository, if there is any additional work please let me know!

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

Best Regards,

Jordy

2022-04-11 16:13 UTC, Ka1wa commented
Looks like the fast test is failing because of incomplete mock data. I'll have a look in the morning!

2022-04-13 15:04 UTC, snay2 requested changes

2022-04-14 00:33 UTC, Ka1wa commented on pkg/monitor/sqsevent/sqs-monitor.go
> +		providerID = fmt.Sprintf("aws:///%s/%s", *instance.Placement.AvailabilityZone, instanceID)
I wasn't able to find any documentation either. The best thing was the source code in the [kubernetes/cloud-provider-aws](https://github.com/kubernetes/cloud-provider-aws) repository.

https://github.com/kubernetes/cloud-provider-aws/blob/5f394ba297bf280ceb3edfc38922630b4bd83f46/pkg/providers/v2/instances.go#L234-L247
```go
// getInstanceProviderID returns the provider ID of an instance which is ultimately set in the node.Spec.ProviderID field.
// The well-known format for a node's providerID is:
//    * aws:///<availability-zone>/<instance-id>
func getInstanceProviderID(instance *ec2.Instance) (string, error) {
	if aws.StringValue(instance.Placement.AvailabilityZone) == "" {
		return "", errors.New("instance availability zone was not set")
	}

	if aws.StringValue(instance.InstanceId) == "" {
		return "", errors.New("instance ID was not set")
	}

	return "aws:///" + aws.StringValue(instance.Placement.AvailabilityZone) + "/" + aws.StringValue(instance.InstanceId), nil
}
```

The return value matches the format I implemented here as well. Hope that it's sufficient proof!

2022-04-14 14:12 UTC, snay2 commented on pkg/monitor/sqsevent/sqs-monitor.go
> +		providerID = fmt.Sprintf("aws:///%s/%s", *instance.Placement.AvailabilityZone, instanceID)
Perfect, that's exactly what I was looking for.

2022-04-14 14:12 UTC, snay2 approved these changes

2022-04-14 15:12 UTC, merged