Dennisme/rebase pod events
aws/aws-node-termination-handler pull request #631
Opened 2022-04-21 18:21 UTC by dennisme

**Issue #, if available:**

**Description of changes:**
This PR rebases an [earlier PR](https://github.com/newrelic-forks/aws-node-termination-handler/pull/1) on our fork that adds  pod eventing to draining. We have been running this for a few months and it does help a ton with visibility. 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2022-04-21 18:50 UTC, dennisme commented
Tests failing locally 

```
2022/04/21 18:46:09 INF Error when trying to list Nodes w/ label, falling back to direct Get lookup of node
2022/04/21 18:46:09 INF Pods on node node_name=e2e-test-7621cf83-worker pod_names=["e2e-test-7621cf83-aemm-amazon-ec2-metadata-mock-5445f44f8fjk9zw","regular-pod-test-b5fb5fc6-jfttf","webhook-test-proxy-hdm49","e2e-test-7621cf83-anth-aws-node-termination-handler-j5zkb","kindnet-mcj95","kube-proxy-vhc7n"]
2022/04/21 18:46:09 INF Error when trying to list Nodes w/ label, falling back to direct Get lookup of node
2022/04/21 18:46:09 INF Draining the node
2022/04/21 18:46:09 INF Error when trying to list Nodes w/ label, falling back to direct Get lookup of node
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x1b39097]

goroutine 113 [running]:
github.com/aws/aws-node-termination-handler/pkg/observability.(*K8sEventRecorder).AnnotatedEventf(0xc000848200, 0x24d7808, 0xc00044fc70, 0xc000873350, 0x21a2e27, 0x6, 0x21a8219, 0xb, 0x21c484b, 0x1d, ...)
	<autogenerated>:1 +0x37
github.com/aws/aws-node-termination-handler/pkg/node.Node.CordonAndDrain(0x0, 0xc00004003a, 0x18, 0xc00003e059, 0x39, 0xc000048016, 0x46, 0x101, 0xc0000401f8, 0x9, ...)
	/node-termination-handler/pkg/node/node.go:140 +0x515
main.cordonAndDrainNode(0x0, 0xc00004003a, 0x18, 0xc00003e059, 0x39, 0xc000048016, 0x46, 0x101, 0xc0000401f8, 0x9, ...)
	/node-termination-handler/cmd/node-termination-handler.go:404 +0x12b
main.drainOrCordonIfNecessary(0xc000256240, 0xc0006741e0, 0x0, 0xc00004003a, 0x18, 0xc00003e059, 0x39, 0xc000048016, 0x46, 0x101, ...)
	/node-termination-handler/cmd/node-termination-handler.go:354 +0x665
created by main.main
	/node-termination-handler/cmd/node-termination-handler.go:247 +0x1107
⏰ Took 988sec
```

2022-05-03 16:19 UTC, brycahta commented
@dennisme thanks for the PR. Could you include the issue # or requested feature in the description? If no issue exists, please open one with some context as to why these changes are needed/beneficial.

2022-05-03 18:01 UTC, dennisme commented
> @dennisme thanks for the PR. Could you include the issue # or requested feature in the description? If no issue exists, please open one with some context as to why these changes are needed/beneficial.

Yes of course! Also next commit will fix the test 😬

2022-05-04 06:37 UTC, dennisme commented
ok we should be good, test fixed :)

2022-05-09 19:02 UTC, brycahta requested changes

2022-05-09 19:17 UTC, snay2 commented on pkg/node/node.go
> +	PodEvictMsg = "Pod evicted due to node drain"
Is this sufficient detail for the event? Do you need it to specify that node-termination-handler initiated the drain in response to a particular AWS event (Spot ITN, ASG event, etc.)?

2022-05-09 19:17 UTC, snay2 commented on pkg/node/node.go
> +				recorder.AnnotatedEventf(podRef, annotations, "Normal", PodEvictReason, PodEvictMsg)
Should `"Normal"` also be in a constant, like `PodEvictReason` and `PodEvictMsg`? What are the other possible values for that argument?

2022-05-09 19:17 UTC, snay2 commented on pkg/observability/k8s-events.go
> +	broadcaster.StartRecordingToSink(&typedcorev1.EventSinkImpl{Interface: clientSet.CoreV1().Events("")})
Can you provide some context on this change? What is the difference in behavior between `"default"` and `""`?

2022-05-09 22:45 UTC, AustinSiu commented on pkg/node/node.go
> +	AnnotatedEventf(object runtime.Object, annotations map[string]string, eventtype, reason, messageFmt string, args ...interface{})
nit: `eventtype` -> `eventType`

2022-05-10 05:41 UTC, dennisme commented on pkg/node/node_test.go
> +	fakeRecorder := record.NewFakeRecorder(100)
Probably not, but if it set to small the tests will hang indefinitely.

2022-05-10 05:41 UTC, dennisme commented on pkg/node/node_test.go
> +	controllerBool := true
Good call

2022-05-10 05:42 UTC, dennisme commented on pkg/node/node.go
> +	AnnotatedEventf(object runtime.Object, annotations map[string]string, eventtype, reason, messageFmt string, args ...interface{})
Yes good catch. I agree.

2022-05-31 17:09 UTC, closed without merging