update dev guide and resources
aws/aws-node-termination-handler pull request #660
Opened 2022-07-13 18:56 UTC by cjerad

**Issue #, if available:**

**Description of changes:**

* `make apply` now uses the value of `CLUSTER_NAMESPACE` rather than a hardcoded namespace
* EventBridge rule name suffixes have been shorted to reduce likelihood of exceeding length limitation
* EKS cluster template now specifies Kuberentes v1.22
* `ko` is now installed from a pre-built binary rather than using `go install` to workaround a build issue in the ko project
* Dev guide now has instructions for verifying that an existing cluster has an IAM OIDC provider, and how to add one
* Dev guide now has steps to run `make help` and `make test`
* Dev guide now has an optional step to display all NTH v2 resources in the cluster
* Dev guide now has a list of tools used
* Dev guide steps and instructions have been revised and improved
* `Terminator` objects will now appear in the "all" category (e.g. `kubectl get all -n <namespace>`)
* Terminator template now specifies a namespace taken from `CLUSTER_NAMESPACE`

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2022-07-15 18:31 UTC, snay2 approved these changes
LGTM, this resolves the issues I had.

2022-07-18 16:32 UTC, pdk27 requested changes

2022-07-18 16:32 UTC, pdk27 commented on Makefile
> +		--namespace ${CLUSTER_NAMESPACE} \
The `delete` target still has hard-coded namespace. Should be $CLUSTER_NAMESPACE?

2022-07-19 16:17 UTC, LikithaVemulapalli approved these changes
/lgtm 👍

2022-07-19 19:12 UTC, pdk27 approved these changes

2022-07-20 15:57 UTC, brycahta approved these changes
/lgtm

2022-07-21 16:13 UTC, AustinSiu approved these changes
lgtm thanks Jerad 👍

2022-07-21 16:40 UTC, merged