eks-charts to ECR Public migration
aws/aws-node-termination-handler pull request #803
Opened 2023-04-03 18:04 UTC by LikithaVemulapalli

## eks-charts to ECR Public migration

**Description of changes:**

We will be hosting our helm charts in `aws-ec2/helm/aws-node-termination-handler`.

- Removed all the scripts related to eks-charts.
- Modified workflow to trigger pushing helm-charts to ECR Public Repository after building images.
- Added helm login script as authentication required to push helm charts.
- Added scripts to add/update repo and push helm charts to ECR repository.
- Modified helm installation README and our repo README instructions to install helm charts using OCI format.
- Modified and removed tests that pull helm charts from eks-charts.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2023-04-05 19:31 UTC, cjerad commented on scripts/push-helm-charts
> +    #shell-check source=$REPO_ROOT_PATH
Specifically, line 47

2023-04-05 20:29 UTC, LikithaVemulapalli commented on README.md
> +For a full list of configuration options see our [Helm readme](https://github.com/aws/aws-node-termination-handler/tree/main/config/helm/aws-node-termination-handler#readme).
Correct me if I'm wrong, if there is a new release later with updated Readme that has all the modified helm installation instructions, I think that would be better to point it to specific version right? If not I can change this one to point it to `/blob/v1.19.0` if we shouldn't use `tree/main`

2023-04-05 20:30 UTC, LikithaVemulapalli commented on scripts/prepare-for-release
Did you mean `prep-for-release` or `release-prep` as I haven't changed the name for this script.

2023-04-05 20:33 UTC, LikithaVemulapalli commented on scripts/push-helm-charts
> +            -r          HELM CHART REPO: Set the helm chart repo
My bad, not at all intentional to use underscore, as I was modifying these scripts multiple times, somehow used underscore in the final one, will change it to align with other variables, will modify the description as well! Thanks for noticing :)

2023-04-05 20:35 UTC, LikithaVemulapalli commented on scripts/push-helm-charts
> +    #shell-check source=$REPO_ROOT_PATH
Yes, initially on calling the login script in line 48, threw me few errors where I need to use directives, and on checking the official document, they provided the syntax on how to use these directives on calling one script from another, and if I don't include line 47 shellcheck tests will fail.

2023-04-05 20:37 UTC, LikithaVemulapalli commented on scripts/push-helm-charts
> +fi
Got it, thanks for the suggestion 👍

2023-04-06 14:15 UTC, LikithaVemulapalli commented on Makefile
> +LATEST_COMMIT_CHART_VERSION=$(shell git --no-pager show ${LATEST_COMMIT_HASH}:config/helm/aws-node-termination-handler/Chart.yaml | grep 'version:' | xargs | cut -d' ' -f2 | tr -d '[:space:]')
Yes, you are right, will change accordingly, thanks for noticing :)

2023-04-06 16:31 UTC, cjerad commented on README.md
> +For a full list of configuration options see our [Helm readme](https://github.com/aws/aws-node-termination-handler/tree/main/config/helm/aws-node-termination-handler#readme).
The `prepare-for-release` script updates version numbers in `README.md`. For an example, see v1.19 release prep [PR](https://github.com/aws/aws-node-termination-handler/pull/760/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5).

2023-04-06 16:33 UTC, cjerad commented on scripts/prepare-for-release
I was referring to the removal of the word "prep" within the file.

2023-04-06 16:34 UTC, LikithaVemulapalli commented on README.md
> +For a full list of configuration options see our [Helm readme](https://github.com/aws/aws-node-termination-handler/tree/main/config/helm/aws-node-termination-handler#readme).
got it! Thanks for the clarification 👍

2023-04-06 19:51 UTC, LikithaVemulapalli commented on scripts/push-helm-charts
> +    #shell-check source=$REPO_ROOT_PATH
As per offline discussion, modified the script to call login script from Make file instead of calling it in `push-helm-chart` script.

2023-04-06 19:52 UTC, LikithaVemulapalli commented on scripts/prepare-for-release
Reverted changes that I made within the `prepare-for-release` script.

2023-04-10 18:48 UTC, cjerad requested changes

2023-04-10 18:48 UTC, cjerad commented on .github/workflows/release.yaml
> +      run: make push-helm-charts
```suggestion
      run: make push-helm-chart
```

Update to match make target name.

2023-04-10 18:48 UTC, cjerad commented on scripts/push-helm-chart
> +  Usage: push-helm-charts
```suggestion
  Usage: push-helm-chart
```

Update to match filename.

2023-04-14 20:04 UTC, cjerad approved these changes

2023-04-14 20:07 UTC, merged