docs: Cleanup installation process for Queue Processor
aws/aws-node-termination-handler pull request #862
Opened 2023-07-11 08:26 UTC by yeahservice

**Issue #, if available:**

**Description of changes:**
While going over the installation process for a test setup I noticed some small QoL changes.

* Remove the leading `$ ` for code blocks, makes them functional when copy pasting them to a terminal
* Remove invalid `"SqsManagedSseEnabled": true` from the queue attributes
  * When executing `sqs create-queue` this returns the error: `Invalid type for parameter Attributes.SqsManagedSseEnabled, value: True, type: <class 'bool'>, valid types: <class 'str'>`
  * According to https://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/sqs-configure-sse-existing-queue.html encryption is enabled by default anyway. Also details on SQS encryption are outlined below the code block.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2023-07-11 15:46 UTC, cjerad requested changes
Hi! Thanks for the contribution.  To keep the doc formatting consistent please also remove the leading `$` from command blocks in BUILD.md

2023-07-11 15:46 UTC, cjerad commented on README.md
> -  "SqsManagedSseEnabled": true
Please keep this attribute. Adding quotes around the value (i.e. `"true"`) will fix the error.

2023-07-19 07:48 UTC, yeahservice commented
I've removed the `$` from BUILD.md as well.

2023-07-19 17:54 UTC, cjerad approved these changes
Thanks for contributing!

2023-07-19 17:56 UTC, merged